### PR TITLE
Update ingress spec to support v1

### PR DESCRIPTION
**Pull request by brandon099**
Updates the ingress template to support `networking.k8s.io/v1` Ingress.

Fixes ressu/kube-plex#23

### CODE REVIEW

**Comment by pixil98** [comment]
I think the only other change you'd want is to bump the version in chart to 0.3.1 since the chart is changing.

**Comment by brandon099** [comment]
Yeah, good catch @pixil98 -- thanks!

**Comment by pixil98** [comment]
I can confirm that this fixes the ingress.

**Comment by ressu** [comment]
Thank you for fixing this!

**Pull request merged**
