### PR TITLE
Support changing paths on the ingress

### PR DESCRIPTION
**Pull request by UnstoppableMango**
This introduces a breaking change, if that is not preferred I have [another branch](https://github.com/UnstoppableMango/ressu-kube-plex/commit/267f41edbb9d5f12b28119a4f276198b9ec778af) with the same change in a non-breaking fashion.

Sorry for the PR spam 😅 I was happy to find a maintained chart for this

### CODE REVIEW

**Comment by ressu** [comment]
Whoops, I saw this after I had already merged the other fix. But I think I actually prefer this solution over the current option.

**Comment by UnstoppableMango** [comment]
You're good! I hadn't actually opened a PR for the alternative, it was just a branch in my fork. I've rebased to fix the merge conflict in the README!

**Comment by ressu** [comment]
Honestly I want to merge this as is. But I keep thinking about backwards compatibility. A quick way to fix that would be to do a check in the template whether it's a string or array. 

Honestly, I don't know if it's worth the effort though.

**Comment by UnstoppableMango** [comment]
I learned about `kindIs` today, I've updated the impl to use that to check for a string host. How does that look?

You're right, it probably wasn't worth the effort but I think it turned out pretty ok 😄

**Comment by ressu** [comment]
Looks good. Thanks!

**Comment by heliochronix** [comment]
I noticed this results in the deployment template setting ADVERTISE_IP to a map[] value rather than the actual FQDNs:
```
         - name: ADVERTISE_IP
           value: |
-            https://plex.domain.tld
-            ,https://plex.domain.tld:443
+            https://map[host:plex.domain.tld]
+            ,https://map[host:plex.domain.tld]:443
```

Is that okay or should the deployment.yaml template be fixed?

**Comment by UnstoppableMango** [comment]
That's probably not right, but I'm not 100% sure. I'll take a look. Sorry if I introduced a bug!

**Comment by UnstoppableMango** [comment]
Yep, I broke it. Working on a fix!

**Comment by ressu** [comment]
Oh right, the advertise ip gets adjusted based on the ingress address too. To be fair, the whole block could be simplified quite a bit as it's doing the same thing in 2 blocks.

https://github.com/ressu/kube-plex/blob/561cbecef3f4e8b7ccc29d31729892957ca74258/charts/kube-plex/templates/deployment.yaml#L141-L155

**Pull request merged**
